global:
  tlsDisable: false
  enabled: true

server:
  enabled: true
  image:
    repository: hashicorp/vault
    tag: 1.15.0
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: istio
    hosts:
      - host: vault-dev.example.com
        paths:
          - path: /
            pathType: Prefix
      - host: vault-uat.example.com
        paths:
          - path: /
            pathType: Prefix
      - host: vault-prod.example.com
        paths:
          - path: /
            pathType: Prefix
  service:
    type: ClusterIP
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

ui:
  enabled: true
  serviceType: ClusterIP 