global:
  tlsDisable: false
  enabled: true

server:
  enabled: true
  image:
    repository: hashicorp/vault
    tag: 1.15.0
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: istio
    hosts:
      - host: vault-dev.psvoltaire.ca
        paths:
          - path: /
            pathType: Prefix
      - host: vault-uat.psvoltaire.ca
        paths:
          - path: /
            pathType: Prefix
      - host: vault-prod.psvoltaire.ca
        paths:
          - path: /
            pathType: Prefix
  service:
    type: ClusterIP
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

ui:
  enabled: true
  serviceType: ClusterIP

bank-vaults:
  image:
    repository: banzaicloud/bank-vaults
    tag: 1.21.0
  vault:
    image:
      repository: hashicorp/vault
      tag: 1.15.0
    config:
      listener:
        tcp:
          address: "[::]:8200"
          tls_disable: false
      storage:
        raft:
          path: /vault/data
      service_registration:
        kubernetes: {}
      ui: true
  unsealer:
    image:
      repository: banzaicloud/bank-vaults
      tag: 1.21.0
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: istio
    hosts:
      - host: vault-dev.psvoltaire.ca
        paths:
          - path: /
            pathType: Prefix
      - host: vault-uat.psvoltaire.ca
        paths:
          - path: /
            pathType: Prefix
      - host: vault-prod.psvoltaire.ca
        paths:
          - path: /
            pathType: Prefix
  service:
    type: ClusterIP
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m" 