apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: vault-oci
  namespace: argocd
stringData:
  url: ghcr.io/bank-vaults/helm-charts
  name: vault-oci
  project: default
  type: helm
  enableOCI: "true"