# argo/argocd-cm-patch.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-virtualservice-template
  namespace: argocd
data:
  template: |
    {{`{{- $env := .env -}}`}}
    {{`{{- $host := .host -}}`}}
    apiVersion: networking.istio.io/v1beta1
    kind: VirtualService
    metadata:
      name: vault-{{`{{$env}}`}}
      namespace: vault-{{`{{$env}}`}}
    spec:
      hosts:
        - {{`{{$host}}`}}
      gateways:
        - istio-system/vault-gateway
      http:
        - route:
            - destination:
                host: vault.vault-{{`{{$env}}`}}.svc.cluster.local
                port:
                  number: 8200
