apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vault-dev
  namespace: vault-dev
spec:
  hosts:
    - vault-dev.psvoltaire.ca
  gateways:
    - istio-system/vault-gateway
  http:
    - route:
        - destination:
            host: vault.vault-dev.svc.cluster.local
            port:
              number: 8200
      match:
        - uri:
            prefix: /