apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: vault
  namespace: vault-dev
spec:
  host: vault.vault-dev.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: vault-dev
  namespace: vault-dev
spec:
  hosts:
    - vault-dev.psvoltaire.ca
  gateways:
    - istio-system/vault-gateway
  http:
    - route:
        - destination:
            host: vault
            port:
              number: 8200