name: Build and Release CLI

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build CLI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          # Create output directory
          mkdir -p dist
          
          # Set binary name based on OS
          if [ "$GOOS" = "windows" ]; then
            BINARY_NAME="vault-promoter.exe"
          else
            BINARY_NAME="vault-promoter"
          fi
          
          # Build the binary with proper flags for each platform
          CGO_ENABLED=0 go build -ldflags="-s -w" -o dist/${BINARY_NAME} ./cmd/cli
          
          # Copy the example config file to dist directory
          cp .vaultconfigs.example dist/
          
          # Create archive with platform-specific naming
          if [ "$GOOS" = "windows" ]; then
            cd dist && zip vault-promoter-${{ matrix.goos }}-${{ matrix.goarch }}.zip ${BINARY_NAME} .vaultconfigs.example && cd ..
          else
            cd dist && tar -czvf vault-promoter-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz ${BINARY_NAME} .vaultconfigs.example && cd ..
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vault-promoter-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*
          if-no-files-found: error

  release:
    name: Create Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v3.1.2
        with:
          path: artifacts

      - name: List all artifacts
        run: find artifacts -type f | sort

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            ## Vault Promoter CLI Release
            
            ### Executables
            - Windows: `vault-promoter-windows-amd64.zip`, `vault-promoter-windows-arm64.zip`
            - macOS: `vault-promoter-darwin-amd64.tar.gz`, `vault-promoter-darwin-arm64.tar.gz`
            - Linux: `vault-promoter-linux-amd64.tar.gz`, `vault-promoter-linux-arm64.tar.gz`
            
            Each archive contains the executable and an example config file (.vaultconfigs.example).
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-executables:
    name: Publish Standalone Executables
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3.1.2
        with:
          path: executables
      
      - name: List executables
        run: find executables -type f | sort
      
      - name: Prepare executables for publishing
        run: |
          mkdir -p dist
          # Extract all archives to get the executables
          for archive in executables/vault-promoter-*/vault-promoter-*.zip; do
            if [ -f "$archive" ]; then
              unzip -o "$archive" -d dist/
            fi
          done
          
          for archive in executables/vault-promoter-*/vault-promoter-*.tar.gz; do
            if [ -f "$archive" ]; then
              tar -xzf "$archive" -C dist/
            fi
          done
          
          # Rename executables with platform suffix for clarity
          if [ -f dist/vault-promoter.exe ]; then
            for platform in windows-amd64 windows-arm64; do
              if [ -f executables/vault-promoter-$platform/vault-promoter-$platform.zip ]; then
                cp dist/vault-promoter.exe dist/vault-promoter-$platform.exe
              fi
            done
          fi
          
          if [ -f dist/vault-promoter ]; then
            for platform in linux-amd64 linux-arm64 darwin-amd64 darwin-arm64; do
              if [ -f executables/vault-promoter-$platform/vault-promoter-$platform.tar.gz ]; then
                cp dist/vault-promoter dist/vault-promoter-$platform
              fi
            done
          fi
          
          ls -la dist/
      
      - name: Upload executables to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: standalone-executables
          path: dist/
          retention-days: 30
      
      - name: Publish executables to GitHub Releases
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    name: Build and Push Docker Image
    needs: build
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
